### ISSUE TITLE
LaunchDarkly relay proxy error logs

### ISSUE THREAD

**Issue by hsy3418** [launchdarkly/ld-relay#170]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
The relay proxy logs keeps showing `Unexpected error while sending events: Post "https://events.launchdarkly.com/diagnostic": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` even when there is 0 connection to this relay proxy.
**To reproduce**
relay proxy 6.6.4 is deployed as a GCP cloud run service. The configurations are mostly used default value, we only configured AUTO_CONFIG_KEY, and USE_EVENTS and route the traffic to a proxy that will connect to our company squid proxy that egress traffic to LaunchDarkly. 
```
        env:
        - name: AUTO_CONFIG_KEY
          valueFrom:
            secretKeyRef:
              key: '3'
              name: [gsm_key1]
        - name: https_proxy
          valueFrom:
            secretKeyRef:
              key: '3'
              name: [gsm_key2]
        - name: http_proxy
          valueFrom:
            secretKeyRef:
              key: '3'
              name: [gsm_key3]
        - name: no_proxy
          value: .run.app,.googleapis.com
        - name: USE_EVENTS
          value: 'true'
        resources:
          limits:
            cpu: 2000m
            memory: 8000Mi
```
So the relay proxy is running fine, we did test by checking flag data using the relay proxy, and we also try to send events, which is also working fine, but this logs seems a bit annoying and not sure why it is keep popping up, even though there isn't any request to send events, and we are not sure at this stage what this error really indicated. 
**Expected behavior**
No error logs shows that related to requests to events endpoint

**Logs**
If applicable, add any log output related to your problem.
<img width="1681" alt="Screen Shot 2022-03-04 at 12 52 37 pm" src="https://user-images.githubusercontent.com/15043076/156683958-821b1122-a7fd-44d8-87db-8214b2dd853e.png">

**SDK version**
NO SDK is used, just using curl for testing purpose, but this error shows regardless if there is request or not.

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
CloudRun

**Additional context**
We have raised a support ticket https://support.launchdarkly.com/hc/en-us/requests/19498 but it's been 20 days, and the last reply from the support is they are still looking into it, so want to try here to see if there is any luck.
