### ISSUE TITLE
LD relay fails to reconnect to Redis after Redis restarts

### ISSUE THREAD

**Issue by carlosjgp** [launchdarkly/ld-relay#207]
https://support.launchdarkly.com/hc/en-us/requests/new

**Describe the bug**
LD relay fails to connect to Redis after Redis has restarted

**To reproduce**
- Install LD relay Helm chart
- Install Bitnami Redis chart version `16.5.0`
```
architecture: standalone
master:
  persistence:
    enabled: false
    medium: Memory
    sizeLimit: 30Mi
```

**Expected behavior**
Fast automatic recovery whether this is fallback to "relay without store" or reconnect to Redis

**Logs**
If applicable, add any log output related to your problem.
![image](https://user-images.githubusercontent.com/1277613/205112336-9f031e04-e0ed-42c5-ae95-bb240d9b9c9e.png)

**SDK version**
- NodeJSClient_6.4.1
- PythonClient_7.5.1

**Language version, developer tools**
N/A

**OS/platform**
- LaunchDarkly relay version 6.7.14

**Additional context**
possibly related to https://github.com/go-redis/redis/issues/1737

Using Sentinel could mitigate this
https://github.com/launchdarkly/ld-relay/issues/114
